/**
 * AUTO-GENERATED by `npm run hobbit-library:sync-registry` (also runs at the start of `npm run hobbit-library:docs`).
 * Do not edit the `registry` array by hand. Add `export const meta` to a reusable component under `src/hobbit-library/components/` (the `meta-preview/` folder is skipped).
 */

export type HobbitLibraryComponentMeta = {
  name: string;
  description?: string;
  variants?: string[];
};

export type HobbitLibraryRegistryEntry = {
  /**
   * Path to the component file relative to repo root, e.g. `src/hobbit-library/components/ButtonPrimary.tsx`.
   * Used by docs tooling and kept in sync by the sync script.
   */
  filePath: string;
  meta: HobbitLibraryComponentMeta;
};

export const registry: HobbitLibraryRegistryEntry[] = [
  {
    filePath: "src/hobbit-library/components/HobbitBanner.tsx",
    meta: {
      name: "HobbitBanner",
      description: "Full-width top strip for announcements or page context in forest tones.",
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitButton.tsx",
    meta: {
      name: "HobbitButton",
      description: "Action button with gold primary, ghost, and outline-gold styles.",
      variants: ["primary", "ghost", "outline-gold"],
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitFooter.tsx",
    meta: {
      name: "HobbitFooter",
      description: "Site footer with brand, tagline, and navigation links in forest tones.",
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitHero.tsx",
    meta: {
      name: "HobbitHero",
      description: "Large hero with centered or split layout: eyebrow, title, copy, and optional CTAs.",
      variants: ["centered", "split"],
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitNav.tsx",
    meta: {
      name: "HobbitNav",
      description: "Top navigation bar with brand, links, and a CTA for Hobbit Hole layouts.",
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitPageShell.tsx",
    meta: {
      name: "HobbitPageShell",
      description: "Full-viewport page wrapper with cream background and body typography defaults.",
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitPortfolioCard.tsx",
    meta: {
      name: "HobbitPortfolioCard",
      description: "Project or piece card with 4:3 image, wood tag, title, and spec line below the image.",
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitProcessSteps.tsx",
    meta: {
      name: "HobbitProcessSteps",
      description: "Numbered process step strip for commission or how-it-works flows.",
      variants: ["horizontal", "vertical"],
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitTag.tsx",
    meta: {
      name: "HobbitTag",
      description: "Small pill label for categories, status, or metadata on cards and lists.",
      variants: ["forest", "gold"],
    },
  },
  {
    filePath: "src/hobbit-library/components/HobbitTestimonial.tsx",
    meta: {
      name: "HobbitTestimonial",
      description: "Customer quote display in grid or single featured layout.",
      variants: ["grid", "featured"],
    },
  },
];
